### ISSUE TITLE
Undefined name '_volumeControl'. Try correcting the name to one that is defined, or defining the name.

### ISSUE THREAD

**Issue by khannikkey01** [JiangJuHong/FlutterPerfectVolumeControl#12]
// PerfectVolumeControl _volumeControl = PerfectVolumeControl();
  TextEditingController _textEditingController = TextEditingController();
  bool _isWorking = false;

  @override
  void initState() {
    super.initState();
    _initVolumeUpListener();
  }

  void _initVolumeUpListener() {
    _volumeControl.addListener(() {
      if (_volumeControl.isVolumeUpPressedFor(Duration(seconds: 10))) {
        setState(() {
          _isWorking = true;
        });
        _showAlert();
      } else {
        setState(() {
          _isWorking = false;
        });
      }
    });
  }

**Comment by JiangJuHong** [comment]
Your first line of code has it commented out
