### ISSUE TITLE
Listener stream only start giving values after the first volume change

### ISSUE THREAD

**Issue by dhafinrayhan** [JiangJuHong/FlutterPerfectVolumeControl#2]
When I use `.stream` on a `StreamBuilder`, it seems like the stream only start giving value after the first volume change, so I have to manually await for `.volume` as the initialData.

**Comment by JiangJuHong** [comment]
I'll try to reproduce it. I'll let you know if there's any progress

**Comment by JiangJuHong** [comment]
fix 1.0.5
