### ISSUE TITLE
Cannot change system volume

### ISSUE THREAD

**Issue by AugustWangVeeva** [JiangJuHong/FlutterPerfectVolumeControl#8]
After I changed the system volume to 0 by mac, and get current volume by the PerfectVolumeControl, it always get volume as 0.6000000238418579, and even if I set the volume to 1 by PerfectVolumeControl, the system volume on mac does not change.

**Comment by JiangJuHong** [comment]
Do you use a simulator for debugging? Please test with real equipment. Some functions do not support simulator.

**Comment by JiangJuHong** [comment]
Not sure if #3  it's the same question, waiting for your more information.

**Comment by AugustWangVeeva** [comment]
Yes, the real equipment works. Thank you so much!
